version: '2'

services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_ROOT_PASSWORD=familyapp123456
      - POSTGRES_DATABASE=familyapp_db
      - POSTGRES_PASSWORD=familyapp123456
      - POSTGRES_USER=familyadmin
    ports:
      - 5432:5432
    restart: always

  spring:
    image: spring-boot
    build:
      context: ./spring
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always
  
  django:
    build: ./django/
    ports:
        - 8000:8000
    volumes: 
        - ./django:/familyapp
    command: >
        pipenv run python manage.py runserver 0.0.0.0:8000
    depends_on:
        -   db
    restart: always
  
  frontend:
    build: ./familyapp-front

    ports:
      - '4201:4201'

    volumes:
      - ./familyapp-front:/app
      - /app/node_modules
    
    depends_on:
      - spring
      - django
