# Generated by Django 3.1.1 on 2020-09-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_family_head'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_head',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='family_head', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
