# Generated by Django 3.1.1 on 2020-09-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20200929_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_no',
            field=models.CharField(max_length=255),
        ),
    ]
