# Generated by Django 3.1.2 on 2020-11-05 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_auto_20200929_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='family_head',
            new_name='familyHead',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='family_name',
            new_name='familyName',
        ),
        migrations.RemoveField(
            model_name='family',
            name='group_id',
        ),
        migrations.AddField(
            model_name='family',
            name='groupId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
