# Generated by Django 3.1.2 on 2020-11-05 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20201105_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='familyHead',
            new_name='family_head',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='familyName',
            new_name='family_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='groupId',
        ),
        migrations.AddField(
            model_name='family',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
