# Generated by Django 3.1.2 on 2020-11-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20201105_1410'),
        ('task_list', '0002_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
    ]
